### PR TITLE
Gradient dropping

### PR DESCRIPTION
**Pull request by afaji**
implementation of this : https://arxiv.org/abs/1704.05021

disabled by default. Set --drop-rate 0.99 to enable.

@kpu

### CODE REVIEW

**Comment by emjotde** [comment]
Conflicting signals :)
Should I pull it or wait until it's not in testing?

**Comment by kpu** [comment]
If it's not breaking existing functionality and worked well enough for the paper, I'd say put in master then expect another commit with a regression test.

**Comment by afaji** [comment]
So far everything seems good.

**Comment by afaji** [comment]
Result so far, with 4 GPUs: (Yes, Azure is slow)
```
[2017-04-21 08:40:22] Ep. 1 : Up. 1000 : Sen. 80000 : Cost 152.77 : Time 687.03s : 2899.46 words/s
[2017-04-21 08:51:11] Ep. 1 : Up. 2000 : Sen. 160000 : Cost 123.89 : Time 641.85s : 3098.61 words/s
[2017-04-21 09:02:11] Ep. 1 : Up. 3000 : Sen. 240000 : Cost 106.49 : Time 653.68s : 3043.44 words/s
[2017-04-21 09:13:12] Ep. 1 : Up. 4000 : Sen. 320000 : Cost 94.49 : Time 652.80s : 3048.29 words/s
[2017-04-21 09:24:15] Ep. 1 : Up. 5000 : Sen. 400000 : Cost 85.33 : Time 654.96s : 3034.84 words/s
[2017-04-21 09:35:25] Ep. 1 : Up. 6000 : Sen. 480000 : Cost 78.85 : Time 662.45s : 3007.23 words/s
[2017-04-21 09:46:31] Ep. 1 : Up. 7000 : Sen. 560000 : Cost 73.56 : Time 659.43s : 3009.28 words/s
[2017-04-21 09:57:29] Ep. 1 : Up. 8000 : Sen. 640000 : Cost 69.70 : Time 650.87s : 3053.53 words/s
[2017-04-21 10:08:34] Ep. 1 : Up. 9000 : Sen. 720000 : Cost 66.79 : Time 659.52s : 3009.26 words/s
[2017-04-21 10:19:43] Ep. 1 : Up. 10000 : Sen. 800000 : Cost 64.28 : Time 662.93s : 3006.70 words/s
[2017-04-21 10:31:16] Ep. 1 : Up. 11000 : Sen. 880000 : Cost 62.25 : Time 686.71s : 2901.64 words/s
[2017-04-21 10:42:19] Ep. 1 : Up. 12000 : Sen. 960000 : Cost 60.55 : Time 656.81s : 3033.83 words/s
[2017-04-21 10:53:25] Ep. 1 : Up. 13000 : Sen. 1040000 : Cost 58.90 : Time 659.81s : 3013.93 words/s
[2017-04-21 11:04:44] Ep. 1 : Up. 14000 : Sen. 1120000 : Cost 57.33 : Time 671.83s : 2958.57 words/s
[2017-04-21 11:15:53] Ep. 1 : Up. 15000 : Sen. 1200000 : Cost 56.22 : Time 662.93s : 3006.97 words/s
[2017-04-21 11:27:09] Ep. 1 : Up. 16000 : Sen. 1280000 : Cost 55.21 : Time 670.46s : 2966.14 words/s
[2017-04-21 11:38:22] Ep. 1 : Up. 17000 : Sen. 1360000 : Cost 54.25 : Time 666.54s : 2984.63 words/s
[2017-04-21 11:49:31] Ep. 1 : Up. 18000 : Sen. 1440000 : Cost 53.33 : Time 662.63s : 3003.55 words/s
[2017-04-21 12:00:44] Ep. 1 : Up. 19000 : Sen. 1520000 : Cost 52.53 : Time 666.35s : 2988.59 words/s
[2017-04-21 12:11:52] Ep. 1 : Up. 20000 : Sen. 1600000 : Cost 51.89 : Time 661.12s : 3013.69 words/s
[2017-04-21 12:23:41] Ep. 1 : Up. 21000 : Sen. 1680000 : Cost 51.51 : Time 699.31s : 2847.21 words/s
[2017-04-21 12:34:45] Ep. 1 : Up. 22000 : Sen. 1760000 : Cost 50.75 : Time 654.52s : 3042.15 words/s
[2017-04-21 12:45:58] Ep. 1 : Up. 23000 : Sen. 1840000 : Cost 50.21 : Time 663.78s : 2997.07 words/s
```

this is consistent with my baseline result for the paper.

**Comment by emjotde** [comment]
I played around with this now, seems to be highly unstable, at least in master. Immediately, fails 4 out of 5 times with different errors when run on 4 GPUs.

**Comment by emjotde** [comment]
OK, this is actually a memory issue, is there a reason the gradient droping requires so much more memory than normal?

**Comment by kpu** [comment]
It's got a copy of the parameters for accumulating locally both client and server side.

**Comment by emjotde** [comment]
Still seems to be a bug. For a 365 MB model it needs 2.5GB more. That cannot be right?

**Comment by emjotde** [comment]
@afaji Can you comment on this? Is this 2.5G more expected?

**Comment by afaji** [comment]
I need about 6x extra memory per GPU. I'll investigate it more.

**Pull request merged**
