### PR TITLE
Online quantization

### PR DESCRIPTION
**Pull request by ykim362**
### Description
This is a PR to enable online quantization. This makes us to quantize output projection embedding matrix.

List of changes:
- expression_operators - add logic to quantize (pack) online

Added dependencies: none

### How to test
Run a model with online quantization. Add parameters'--optimize --gemm-type {type to quantize}'

### Checklist

- [x] I have tested the code manually
- [x] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
intgemm used to implement this in the past but @emjotde said that the whole tensor caching mechanism would be removed in the future so the feature got removed from the pull request. Is there a change in the development plans?

**Comment by kpu** [comment]
This feature was already in intgemm but removed in the pull request. . . will you reconsider?

**Comment by kpu** [comment]
Not that Nick and I coordinate messages at all

**Comment by ykim362** [comment]
There's a use-case for this online qunatization. In that scenario, a separate branch is used, so it couldn't get all the latest changes.

**Comment by XapaJIaMnu** [comment]
Does it mean it's ready to go into master? Can we get our intgemm online quantization here?

**Comment by ykim362** [comment]
I hope we can get both online quantization into into the master. And, maybe we can support only 8-bit quantizations only, for the online quantization? That may make the code cleaner?

**Comment by XapaJIaMnu** [comment]
We had both 8bit and 16bit, as well online quantisation of the output layer (or the shortlist). We can update those to the upstream version and perhaps merge with you?

**Comment by emjotde** [comment]
@XapaJIaMnu 
For some context. This is needed for an MS-internal team, unfortunately. I am actually not really happy with how we are solving this at the moment and would prefer to not pull it, but have to for the moment. Adding more stuff on-top of this which would cement this solution in more, which would not be great.

**Comment by emjotde** [comment]
@ykim362 this seems to be breaking intgemm, though. Checkout these regression tests:

  - tests/decoder/intgemm/test_intgemm_16bit.sh
  - tests/decoder/intgemm/test_intgemm_16bit_avx2.sh
  - tests/decoder/intgemm/test_intgemm_16bit_sse2.sh
  - tests/decoder/intgemm/test_intgemm_8bit.sh
  - tests/decoder/intgemm/test_intgemm_8bit_avx2.sh
  - tests/decoder/intgemm/test_intgemm_8bit_ssse3.sh
  - tests/models/wnmt18/test_student_small_aan_intgemm16.sh
  - tests/models/wnmt18/test_student_small_aan_intgemm8.sh

All of these now fail with an abort.

**Comment by emjotde** [comment]
Note, some of these may fail on different machines anyway, but due to numeric issues on the outputs, not during actual inference.

**Comment by ykim362** [comment]
Sure, @emjotde . I will check the regression tests.

**Comment by ykim362** [comment]
@emjotde I fixed the regression tests for intgemm. But, the model tests seem broken for the master as well. They give this error. 
This is common for 
  - tests/models/wnmt18/test_student_small_aan.sh
  - tests/models/wnmt18/test_student_small_aan_intgemm16.sh
  - tests/models/wnmt18/test_student_small_aan_intgemm8.sh

```
[2021-05-24 21:32:31] Error: Invalid activation name 'sigmoid'
[2021-05-24 21:32:31] Error: Aborted from std::function<IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase> > >(IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase> > >)> marian::activationByName(const string&) in /data2/youki/marian-dev-external/src/layers/generic.h:182
```

**Comment by emjotde** [comment]
Yes, I have a fix for that. Forgot to push.

**Comment by emjotde** [comment]
Pushed. Thanks for the fix.

**Comment by ykim362** [comment]
The model tests also work fine with the patch. Thanks!

**Review by emjotde — APPROVED** [review]

**Pull request merged**
